"""Exact sag of one body of revolution, in pure NumPy (no SlipPy import).

Used by the ``two_profiles`` builds to turn the principal radii ``(rx, ry)`` of a body, in the
form ``hertz_full`` takes them, into the height array of a discrete SlipPy surface.

Sag convention: ``s(x, y)`` is how far the surface falls away from the tangent plane at the
contact point, towards the body interior [m] (convex > 0, concave < 0, flat = 0). The initial gap of
two bodies is ``s_1 + s_2`` (Johnson, ch. 4) and the SlipPy profile of a discrete surface is
``profile = -s``. Axes: ``X, Y = np.meshgrid(x, y)``.
"""
from __future__ import annotations

import math

import numpy as np

__all__ = ["sag_body"]


def _circle_drop(r: float, s: np.ndarray) -> np.ndarray:
    """Drop of a circle of signed radius ``r`` at distance ``s`` from its apex (exact)."""
    if math.isinf(r):
        return np.zeros_like(s, dtype=float)
    if np.any(np.abs(s) > abs(r)):
        raise ValueError(f"point outside the circle of radius {r:g} m: |s|max = {np.abs(s).max():g} m")
    return r - math.copysign(1.0, r) * np.sqrt(r * r - s * s)


def sag_body(r: tuple[float, float], x: np.ndarray, y: np.ndarray) -> np.ndarray:
    """Return the exact sag of a body from its principal radii ``r = (rx, ry)`` [m].

    The surface is generated by a transverse profile circle of radius ``ry`` swept around an axis
    parallel to ``y`` at distance ``rx`` from the apex: a sphere (``rx == ry``), a cylinder (one
    radius infinite), a flat (both infinite) or a raceway torus (``rx`` rolling radius, ``ry`` the
    negative groove radius).

    Parameters
    ----------
    r : tuple of float
        ``(rx, ry)`` as in ``ContactCase.r1`` / ``r2``: convex > 0, concave < 0, ``math.inf`` for none.
    x, y : numpy.ndarray
        Coordinates [m], same shape.

    Returns
    -------
    numpy.ndarray
        Sag [m], positive for convex bodies.

    Raises
    ------
    ValueError
        If a point lies outside the generating circles (the body does not exist there).

    Notes
    -----
    With ``s_y = ry - sign(ry) sqrt(ry^2 - y^2)`` the local rolling radius at offset ``y`` is
    ``rho = rx - s_y`` and ``s = rx - sign(rx) sqrt(rho^2 - x^2)``; near the apex
    ``s ~ x^2/(2 rx) + y^2/(2 ry)``, the paraboloid assumed by Hertz.

    Examples
    --------
    >>> import numpy as np
    >>> round(float(sag_body((6e-3, 6e-3), np.array(0.3e-3), np.array(0.4e-3))) * 1e6, 3)   # [um]
    20.87
    """
    rx, ry = r
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    s_y = _circle_drop(ry, y)
    if math.isinf(rx):
        return s_y + 0.0 * x
    rho = rx - s_y
    if np.any(np.abs(x) > np.abs(rho)):
        raise ValueError("point outside the rolling circle of the surface of revolution")
    return rx - math.copysign(1.0, rx) * np.sqrt(rho * rho - x * x)
